-- MySQL Script generated by MySQL Workbench
-- 05/12/16 16:41:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`admin` (
  `admin_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `salt` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`admin_id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country` (
  `country_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`country_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film` (
  `film_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NOT NULL COMMENT '',
  `year` INT(11) NOT NULL COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  `description` TEXT NOT NULL COMMENT '',
  `time` INT(11) NULL DEFAULT NULL COMMENT '',
  `img` VARCHAR(256) NULL DEFAULT NULL COMMENT '',
  `trailer` VARCHAR(512) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`film_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`country_has_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`country_has_film` (
  `country_id` INT(11) NOT NULL COMMENT '',
  `film_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`country_id`, `film_id`)  COMMENT '',
  INDEX `fk_country_has_film_film1_idx` (`film_id` ASC)  COMMENT '',
  INDEX `fk_country_has_film_country1_idx` (`country_id` ASC)  COMMENT '',
  CONSTRAINT `fk_country_has_film_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`country` (`country_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_country_has_film_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`film_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `employee_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `date_birth` DATE NULL DEFAULT NULL COMMENT '',
  `img` VARCHAR(256) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`employee_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 174
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`staff` (
  `staff_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `position` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`staff_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`employee_has_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee_has_film` (
  `employee_id` INT(11) NOT NULL COMMENT '',
  `film_id` INT(11) NOT NULL COMMENT '',
  `staff_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`employee_id`, `film_id`, `staff_id`)  COMMENT '',
  INDEX `fk_employee_has_film_film1_idx` (`film_id` ASC)  COMMENT '',
  INDEX `fk_employee_has_film_employee1_idx` (`employee_id` ASC)  COMMENT '',
  INDEX `fk_employee_has_film_staff1_idx` (`staff_id` ASC)  COMMENT '',
  CONSTRAINT `fk_employee_has_film_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_has_film_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`film_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_has_film_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `mydb`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `genre_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`genre_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`film_has_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_has_genre` (
  `film_id` INT(11) NOT NULL COMMENT '',
  `genre_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`film_id`, `genre_id`)  COMMENT '',
  INDEX `fk_film_has_genre_genre1_idx` (`genre_id` ASC)  COMMENT '',
  INDEX `fk_film_has_genre_film1_idx` (`film_id` ASC)  COMMENT '',
  CONSTRAINT `fk_film_has_genre_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`film_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_has_genre_genre1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `mydb`.`genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`language` (
  `language_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`language_id`)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`film_has_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`film_has_language` (
  `film_id` INT(11) NOT NULL COMMENT '',
  `language_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`film_id`, `language_id`)  COMMENT '',
  INDEX `fk_film_has_language_language1_idx` (`language_id` ASC)  COMMENT '',
  INDEX `fk_film_has_language_film1_idx` (`film_id` ASC)  COMMENT '',
  CONSTRAINT `fk_film_has_language_film1`
    FOREIGN KEY (`film_id`)
    REFERENCES `mydb`.`film` (`film_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_has_language_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `mydb`.`language` (`language_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sessions` (
  `session_id` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL COMMENT '',
  `expires` INT(11) UNSIGNED NOT NULL COMMENT '',
  `data` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`session_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
